version: "3"
services:
  api: 
    image: crazynuclei/socialmedia_fastapi
    ports:
      - 80:8000
    depends_on:
      - postgres
    # volumes:
    #   - ./:/usr/src/app:ro
  # env_file: 
  #   - ./.env
    environment: 
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOSTNAME= ${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
  
  postgres: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data 

volumes:
  postgres-db:

